## Pandas - Importing data

In [5]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems_2019_first_6_months.csv``` into a dataframe named ```ems_19_first_df```

In [6]:
## import data and store in dataframe
pd.read_csv("ems_2019_first_6_months.csv")

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [45]:
## call the first 10 rows
ems_19_first_df = pd.read_csv("ems_2019_first_6_months.csv")
ems_19_first_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
5,190073272,2019-01-07 17:49:43,EDP,7,EDP,7,01/07/2019 05:49:50 PM,Y,7,01/07/2019 05:50:04 PM,...,17.0,5.0,106.0,2.0,12.0,N,N,N,N,chunk149.csv
6,190073416,2019-01-07 18:27:54,EDP,7,EDP,7,01/07/2019 06:28:33 PM,Y,39,01/07/2019 06:28:44 PM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk149.csv
7,190081434,2019-01-08 10:28:31,UNKNOW,4,UNKNOW,4,01/08/2019 10:29:19 AM,Y,48,01/08/2019 10:29:36 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk149.csv
8,190081743,2019-01-08 11:43:35,UNKNOW,4,UNKNOW,4,01/08/2019 11:43:47 AM,Y,12,01/08/2019 11:43:55 AM,...,7.0,1.0,103.0,2.0,12.0,N,N,N,N,chunk149.csv
9,190081744,2019-01-08 11:43:48,EDP,7,EDP,7,01/08/2019 11:43:59 AM,Y,11,01/08/2019 11:44:30 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk149.csv

In [46]:
## call the last 5 rows
ems_19_first_df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [47]:
## call a 20 random rows
ems_19_first_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
614367,191524298,2019-06-01 21:03:05,DRUG,4,DRUG,4,06/01/2019 09:03:24 PM,Y,19,06/01/2019 09:03:35 PM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk156.csv
231151,190610122,2019-03-02 00:38:14,STATEP,2,STATEP,2,03/02/2019 12:38:19 AM,Y,5,03/02/2019 12:38:34 AM,...,70.0,45.0,314.0,22.0,9.0,N,N,N,N,chunk152.csv
321061,190830398,2019-03-24 02:18:27,DRUG,4,DRUG,4,03/24/2019 02:18:43 AM,Y,16,03/24/2019 02:18:59 AM,...,110.0,25.0,404.0,24.0,6.0,N,N,N,N,chunk153.csv
639838,191582996,2019-06-07 15:37:51,MVA,6,MVAINJ,4,06/07/2019 03:37:58 PM,Y,7,06/07/2019 03:38:25 PM,...,121.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk156.csv
343031,190882155,2019-03-29 13:04:03,UNKNOW,4,EDP,7,03/29/2019 02:39:31 PM,Y,5728,03/29/2019 02:40:50 PM,...,26.0,7.0,109.0,5.0,13.0,N,N,N,N,chunk153.csv
282134,190733100,2019-03-14 16:53:44,CVAC,2,CVAC,2,03/14/2019 04:56:13 PM,Y,149,03/14/2019 04:56:27 PM,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk152.csv
550916,191382071,2019-05-18 12:43:56,DRUG,4,DRUG,4,05/18/2019 12:44:19 PM,Y,23,05/18/2019 12:44:38 PM,...,45.0,13.0,210.0,8.0,14.0,N,N,N,N,chunk155.csv
111260,190310506,2019-01-31 04:53:47,CARDBR,2,CARDBR,2,01/31/2019 04:54:01 AM,Y,14,01/31/2019 04:54:54 AM,...,123.0,51.0,503.0,31.0,11.0,N,N,N,N,chunk150.csv
428634,191084230,2019-04-18 22:27:47,SICK,6,SICK,6,04/18/2019 10:28:03 PM,Y,16,04/18/2019 10:28:18 PM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk154.csv
448673,191134343,2019-04-23 22:47:45,EDP,7,EDP,7,04/23/2019 10:47:52 PM,Y,7,04/23/2019 10:48:06 PM,...,107.0,24.0,408.0,28.0,6.0,N,N,N,N,chunk154.csv
690888,191701640,2019-06-19 11:31:11,STATEP,2,STATEP,2,06/19/2019 11:31:21 AM,Y,10,06/19/2019 11:31:32 AM,...,14.0,3.0,104.0,2.0,10.0,N,N,N,N,chunk156.csv
503861,191272091,2019-05-07 13:06:48,SICK,6,SICK,6,05/07/2019 01:07:40 PM,Y,52,05/07/2019 01:07:48 PM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk154.csv
97564,190273026,2019-01-27 18:14:27,RESPIR,4,RESPIR,4,01/27/2019 06:14:51 PM,Y,24,01/27/2019 06:15:09 PM,...,109.0,20.0,407.0,25.0,6.0,N,N,N,N,chunk150.csv
404984,191031291,2019-04-13 09:15:54,UNKNOW,4,UNKNOW,4,04/13/2019 09:16:04 AM,Y,10,04/13/2019 09:16:11 AM,...,1.0,1.0,101.0,2.0,10.0,N,N,N,N,chunk153.csv
348004,190892824,2019-03-30 16:36:17,EDP,7,EDP,7,03/30/2019 04:36:36 PM,Y,19,03/30/2019 04:36:55 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk153.csv
438602,191111684,2019-04-21 11:30:41,STATEP,2,STATEP,2,04/21/2019 11:30:53 AM,Y,12,04/21/2019 11:31:04 AM,...,114.0,26.0,401.0,30.0,12.0,N,N,N,N,chunk154.csv
322019,190831437,2019-03-24 10:18:09,CARD,3,SICK,6,03/24/2019 10:19:35 AM,Y,86,03/24/2019 10:20:04 AM,...,42.0,16.0,203.0,12.0,15.0,N,N,N,N,chunk153.csv
648416,191602535,2019-06-09 14:44:49,INJURY,5,INJURY,5,06/09/2019 02:45:09 PM,Y,20,06/09/2019 02:45:22 PM,...,26.0,9.0,109.0,5.0,13.0,N,N,N,N,chunk156.csv
739898,191810404,2019-06-30 01:50:14,UNKNOW,4,UNKNOW,4,06/30/2019 01:50:33 AM,Y,19,06/30/2019 01:50:59 AM,...,43.0,18.0,209.0,8.0,15.0,N,N,N,N,chunk157.csv
730999,191791020,2019-06-28 07:48:27,INJURY,5,INJURY,5,06/28/2019 07:48:39 AM,Y,12,06/28/2019 07:48:59 AM,...,46.0,14.0,205.0,9.0,15.0,N,N,N,N,chunk157.csv

In [48]:
## get basic overview of the data

## what datatypes do the different columns hold?
#Ansuer: int64, object, float64

## how many rows and columns are there?
##Answer: 32 Columns, 754656 rows



ems_19_first_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754656 entries, 0 to 754655
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 754656 non-null  int64
 1   INCIDENT_DATETIME               754656 non-null  object
 2   INITIAL_CALL_TYPE               754656 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     754656 non-null  int64
 4   FINAL_CALL_TYPE                 754656 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       754656 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       749544 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  754656 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    754656 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       748561 non-null  object
 10  FIRST_ON_SCENE_DATETIME         729221 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  754656 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    729068 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   729221 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          522462 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     518867 non-null  object
 16  INCIDENT_CLOSE_DATETIME         754540 non-null  object
 17  HELD_INDICATOR                  754656 non-null  object
 18  INCIDENT_DISPOSITION_CODE       748265 non-null  float64
 19  BOROUGH                         754656 non-null  object
 20  INCIDENT_DISPATCH_AREA          754656 non-null  object
 21  ZIPCODE                         745086 non-null  float64
 22  POLICEPRECINCT                  745102 non-null  float64
 23  CITYCOUNCILDISTRICT             745071 non-null  float64
 24  COMMUNITYDISTRICT               745101 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         744542 non-null  float64
 26  CONGRESSIONALDISTRICT           745071 non-null  float64
 27  REOPEN_INDICATOR                754656 non-null  object
 28  SPECIAL_EVENT_INDICATOR         754656 non-null  object
 29  STANDBY_INDICATOR               754656 non-null  object
 30  TRANSFER_INDICATOR              754656 non-null  object
 31  source                          754656 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 184.2+ MB

In [49]:
ems_19_first_df.shape

(754656, 32)

### In three separate cells, ingest the 3 other related datasets into this notebook:

- ```ems_2019_last_6_months.csv``` into a dataframe named ```ems_19_last_df```
- ```ems_2020_first_6_months.csv``` into a dataframe named ```ems_20_first_df```
- ```ems_2020_last_6_months.csv``` into a dataframe named ```ems_20_last_df```

We want to combine all 4 dataframes so we can run an analysis on the combined dataframes

In [17]:
ems_19_last_df = pd.read_csv ("ems_2019_last_6_months.csv")

In [40]:
### For last 6 months of 2019
## call the dataframe to see what you have
ems_19_last_df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781740 entries, 0 to 781739
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 781740 non-null  int64
 1   INCIDENT_DATETIME               781740 non-null  object
 2   INITIAL_CALL_TYPE               781740 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     781740 non-null  int64
 4   FINAL_CALL_TYPE                 781740 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       781740 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       776500 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  781740 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    781740 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       775362 non-null  object
 10  FIRST_ON_SCENE_DATETIME         756189 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  781740 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    756044 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   756164 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          526152 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     522569 non-null  object
 16  INCIDENT_CLOSE_DATETIME         781380 non-null  object
 17  HELD_INDICATOR                  781740 non-null  object
 18  INCIDENT_DISPOSITION_CODE       775120 non-null  float64
 19  BOROUGH                         781740 non-null  object
 20  INCIDENT_DISPATCH_AREA          781740 non-null  object
 21  ZIPCODE                         771206 non-null  float64
 22  POLICEPRECINCT                  771235 non-null  float64
 23  CITYCOUNCILDISTRICT             771187 non-null  float64
 24  COMMUNITYDISTRICT               771234 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         770645 non-null  float64
 26  CONGRESSIONALDISTRICT           771187 non-null  float64
 27  REOPEN_INDICATOR                781740 non-null  object
 28  SPECIAL_EVENT_INDICATOR         781740 non-null  object
 29  STANDBY_INDICATOR               781740 non-null  object
 30  TRANSFER_INDICATOR              781740 non-null  object
 31  source                          781740 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 190.9+ MB

In [41]:
### For first 6 months of 2020
## call the dataframe to see what you have
ems_20_first_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741807 entries, 0 to 741806
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 741807 non-null  int64
 1   INCIDENT_DATETIME               741807 non-null  object
 2   INITIAL_CALL_TYPE               741807 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     741807 non-null  int64
 4   FINAL_CALL_TYPE                 741807 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       741807 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       735936 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  741807 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    741807 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       734580 non-null  object
 10  FIRST_ON_SCENE_DATETIME         710059 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  741807 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    710008 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   710059 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          442033 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     437674 non-null  object
 16  INCIDENT_CLOSE_DATETIME         741456 non-null  object
 17  HELD_INDICATOR                  741807 non-null  object
 18  INCIDENT_DISPOSITION_CODE       734627 non-null  float64
 19  BOROUGH                         741807 non-null  object
 20  INCIDENT_DISPATCH_AREA          741807 non-null  object
 21  ZIPCODE                         734365 non-null  float64
 22  POLICEPRECINCT                  734386 non-null  float64
 23  CITYCOUNCILDISTRICT             734386 non-null  float64
 24  COMMUNITYDISTRICT               734386 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         733944 non-null  float64
 26  CONGRESSIONALDISTRICT           734386 non-null  float64
 27  REOPEN_INDICATOR                741807 non-null  object
 28  SPECIAL_EVENT_INDICATOR         741807 non-null  object
 29  STANDBY_INDICATOR               741807 non-null  object
 30  TRANSFER_INDICATOR              741807 non-null  object
 31  source                          741807 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 181.1+ MB

In [42]:
### For last 6 months of 2020
## call the dataframe to see what you have

ems_20_last_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670755 entries, 0 to 670754
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 670755 non-null  int64
 1   INCIDENT_DATETIME               670755 non-null  object
 2   INITIAL_CALL_TYPE               670755 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     670755 non-null  int64
 4   FINAL_CALL_TYPE                 670755 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       670755 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       668991 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  670755 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    670755 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       668017 non-null  object
 10  FIRST_ON_SCENE_DATETIME         653427 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  670755 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    653375 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   653398 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          416375 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     413494 non-null  object
 16  INCIDENT_CLOSE_DATETIME         670662 non-null  object
 17  HELD_INDICATOR                  670755 non-null  object
 18  INCIDENT_DISPOSITION_CODE       668514 non-null  float64
 19  BOROUGH                         670755 non-null  object
 20  INCIDENT_DISPATCH_AREA          670755 non-null  object
 21  ZIPCODE                         661922 non-null  float64
 22  POLICEPRECINCT                  661949 non-null  float64
 23  CITYCOUNCILDISTRICT             661949 non-null  float64
 24  COMMUNITYDISTRICT               661945 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         661365 non-null  float64
 26  CONGRESSIONALDISTRICT           661949 non-null  float64
 27  REOPEN_INDICATOR                670755 non-null  object
 28  SPECIAL_EVENT_INDICATOR         670755 non-null  object
 29  STANDBY_INDICATOR               670755 non-null  object
 30  TRANSFER_INDICATOR              670755 non-null  object
 31  source                          670755 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 163.8+ MB

### Check if all the column headers are identical (down to the same order)
We need to confirm they are the same before we combine them

In [53]:
## headers for first 6 months of 2019
ems_19_first_df.head ()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv

In [54]:
## headers for first 6 months of 2020
ems_20_last_df.head()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201853344,2020-07-03 19:51:35,MVAINJ,4,MVAINJ,4,07/03/2020 07:52:54 PM,Y,79,07/03/2020 07:53:13 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk172.csv
1,201861781,2020-07-04 13:38:45,INJURY,5,INJURY,5,07/04/2020 01:38:55 PM,Y,10,07/04/2020 01:39:01 PM,...,20.0,3.0,107.0,3.0,10.0,N,N,N,N,chunk172.csv
2,201862931,2020-07-04 19:06:08,INJURY,5,INJURY,5,07/04/2020 07:06:34 PM,Y,26,07/04/2020 07:06:53 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk172.csv
3,201870048,2020-07-05 00:09:31,SICK,6,SICK,6,NaN,N,0,NaN,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk172.csv
4,201870159,2020-07-05 00:31:24,EDPC,7,SICK,6,NaN,N,0,NaN,...,43.0,17.0,209.0,12.0,15.0,N,N,N,N,chunk172.csv

In [55]:
## check if they are the same
list (ems_19_first_df.columns)

['CAD_INCIDENT_ID',
 'INCIDENT_DATETIME',
 'INITIAL_CALL_TYPE',
 'INITIAL_SEVERITY_LEVEL_CODE',
 'FINAL_CALL_TYPE',
 'FINAL_SEVERITY_LEVEL_CODE',
 'FIRST_ASSIGNMENT_DATETIME',
 'VALID_DISPATCH_RSPNS_TIME_INDC',
 'DISPATCH_RESPONSE_SECONDS_QY',
 'FIRST_ACTIVATION_DATETIME',
 'FIRST_ON_SCENE_DATETIME',
 'VALID_INCIDENT_RSPNS_TIME_INDC',
 'INCIDENT_RESPONSE_SECONDS_QY',
 'INCIDENT_TRAVEL_TM_SECONDS_QY',
 'FIRST_TO_HOSP_DATETIME',
 'FIRST_HOSP_ARRIVAL_DATETIME',
 'INCIDENT_CLOSE_DATETIME',
 'HELD_INDICATOR',
 'INCIDENT_DISPOSITION_CODE',
 'BOROUGH',
 'INCIDENT_DISPATCH_AREA',
 'ZIPCODE',
 'POLICEPRECINCT',
 'CITYCOUNCILDISTRICT',
 'COMMUNITYDISTRICT',
 'COMMUNITYSCHOOLDISTRICT',
 'CONGRESSIONALDISTRICT',
 'REOPEN_INDICATOR',
 'SPECIAL_EVENT_INDICATOR',
 'STANDBY_INDICATOR',
 'TRANSFER_INDICATOR',
 'source']

In [56]:
list (ems_20_last_df.columns)

['CAD_INCIDENT_ID',
 'INCIDENT_DATETIME',
 'INITIAL_CALL_TYPE',
 'INITIAL_SEVERITY_LEVEL_CODE',
 'FINAL_CALL_TYPE',
 'FINAL_SEVERITY_LEVEL_CODE',
 'FIRST_ASSIGNMENT_DATETIME',
 'VALID_DISPATCH_RSPNS_TIME_INDC',
 'DISPATCH_RESPONSE_SECONDS_QY',
 'FIRST_ACTIVATION_DATETIME',
 'FIRST_ON_SCENE_DATETIME',
 'VALID_INCIDENT_RSPNS_TIME_INDC',
 'INCIDENT_RESPONSE_SECONDS_QY',
 'INCIDENT_TRAVEL_TM_SECONDS_QY',
 'FIRST_TO_HOSP_DATETIME',
 'FIRST_HOSP_ARRIVAL_DATETIME',
 'INCIDENT_CLOSE_DATETIME',
 'HELD_INDICATOR',
 'INCIDENT_DISPOSITION_CODE',
 'BOROUGH',
 'INCIDENT_DISPATCH_AREA',
 'ZIPCODE',
 'POLICEPRECINCT',
 'CITYCOUNCILDISTRICT',
 'COMMUNITYDISTRICT',
 'COMMUNITYSCHOOLDISTRICT',
 'CONGRESSIONALDISTRICT',
 'REOPEN_INDICATOR',
 'SPECIAL_EVENT_INDICATOR',
 'STANDBY_INDICATOR',
 'TRANSFER_INDICATOR',
 'source']

In [57]:
## creater headers list for last 6 months of 2019 and 2020
list (ems_20_last_df.columns) == list (ems_19_first_df.columns)

True

In [ ]:
## check if one of the first is equal to one of the last
## I didn't understand this question

In [ ]:
## now confirm that the two lasts are the same
##I didn't understand this question.

##I compared the four databases and they are the same

In [59]:
list (ems_19_last_df.columns)

['CAD_INCIDENT_ID',
 'INCIDENT_DATETIME',
 'INITIAL_CALL_TYPE',
 'INITIAL_SEVERITY_LEVEL_CODE',
 'FINAL_CALL_TYPE',
 'FINAL_SEVERITY_LEVEL_CODE',
 'FIRST_ASSIGNMENT_DATETIME',
 'VALID_DISPATCH_RSPNS_TIME_INDC',
 'DISPATCH_RESPONSE_SECONDS_QY',
 'FIRST_ACTIVATION_DATETIME',
 'FIRST_ON_SCENE_DATETIME',
 'VALID_INCIDENT_RSPNS_TIME_INDC',
 'INCIDENT_RESPONSE_SECONDS_QY',
 'INCIDENT_TRAVEL_TM_SECONDS_QY',
 'FIRST_TO_HOSP_DATETIME',
 'FIRST_HOSP_ARRIVAL_DATETIME',
 'INCIDENT_CLOSE_DATETIME',
 'HELD_INDICATOR',
 'INCIDENT_DISPOSITION_CODE',
 'BOROUGH',
 'INCIDENT_DISPATCH_AREA',
 'ZIPCODE',
 'POLICEPRECINCT',
 'CITYCOUNCILDISTRICT',
 'COMMUNITYDISTRICT',
 'COMMUNITYSCHOOLDISTRICT',
 'CONGRESSIONALDISTRICT',
 'REOPEN_INDICATOR',
 'SPECIAL_EVENT_INDICATOR',
 'STANDBY_INDICATOR',
 'TRANSFER_INDICATOR',
 'source']

In [60]:
list (ems_20_first_df.columns)

['CAD_INCIDENT_ID',
 'INCIDENT_DATETIME',
 'INITIAL_CALL_TYPE',
 'INITIAL_SEVERITY_LEVEL_CODE',
 'FINAL_CALL_TYPE',
 'FINAL_SEVERITY_LEVEL_CODE',
 'FIRST_ASSIGNMENT_DATETIME',
 'VALID_DISPATCH_RSPNS_TIME_INDC',
 'DISPATCH_RESPONSE_SECONDS_QY',
 'FIRST_ACTIVATION_DATETIME',
 'FIRST_ON_SCENE_DATETIME',
 'VALID_INCIDENT_RSPNS_TIME_INDC',
 'INCIDENT_RESPONSE_SECONDS_QY',
 'INCIDENT_TRAVEL_TM_SECONDS_QY',
 'FIRST_TO_HOSP_DATETIME',
 'FIRST_HOSP_ARRIVAL_DATETIME',
 'INCIDENT_CLOSE_DATETIME',
 'HELD_INDICATOR',
 'INCIDENT_DISPOSITION_CODE',
 'BOROUGH',
 'INCIDENT_DISPATCH_AREA',
 'ZIPCODE',
 'POLICEPRECINCT',
 'CITYCOUNCILDISTRICT',
 'COMMUNITYDISTRICT',
 'COMMUNITYSCHOOLDISTRICT',
 'CONGRESSIONALDISTRICT',
 'REOPEN_INDICATOR',
 'SPECIAL_EVENT_INDICATOR',
 'STANDBY_INDICATOR',
 'TRANSFER_INDICATOR',
 'source']

In [61]:
list (ems_19_first_df.columns) == list (ems_20_last_df.columns) == list (ems_19_last_df.columns) == list (ems_20_first_df.columns)

True

## Combine the 4 dataframes

In [62]:
## create a list to combine all 
com_ems = pd.concat([ems_19_last_df, ems_20_first_df,ems_20_last_df, ems_19_first_df])

In [63]:
## combine the dfs
com_ems

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,191853909,2019-07-04 21:07:53,DRUG,4,DRUG,4,07/04/2019 09:08:16 PM,Y,23,07/04/2019 09:08:26 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
1,191864927,2019-07-05 21:09:53,MVAINJ,4,MVAINJ,4,07/05/2019 09:10:10 PM,Y,17,07/05/2019 09:10:20 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
2,191870823,2019-07-06 05:32:12,INJURY,5,INJURY,5,07/06/2019 05:32:49 AM,Y,37,07/06/2019 05:33:40 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk157.csv
3,191870824,2019-07-06 05:33:49,UNC,2,UNC,2,07/06/2019 05:33:57 AM,Y,8,07/06/2019 05:34:25 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk157.csv
4,191870897,2019-07-06 06:20:26,INJURY,5,INJURY,5,07/06/2019 06:20:43 AM,Y,17,07/06/2019 06:20:53 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

#### Confirm that their row totals add up to the correct number

In [64]:
## how many rows does the combined df have
com_ems.shape

(2948958, 32)

In [71]:
## get total rows when you add up all the individual dataframes

com_ems.shape [0] == ems_19_last_df.shape[0] + ems_19_first_df.shape[0] + ems_20_first_df.shape[0] + ems_20_last_df.shape[0]

True

## Ingest Massive Dataset

Step 1. Open this dataset in Excel first. What happened?

Step 2. Open this data set in Pandas.

In [72]:
## import global_temps.csv into a df called temps_df

temps_df = pd.read_csv("global_temps.csv")

## How many rows of data does this dataset have?

In [73]:
## 2_906_327

temps_df.shape

(2906327, 7)

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

Note that this is an excerpt of the actual CBP data.

In [87]:
### import it here
multi = pd.read_excel("multi-data.xlsx", sheet_name="CBP")

In [88]:
multi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95727 entries, 0 to 95726
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  95722 non-null  object
 1   Unnamed: 1  95224 non-null  object
 2   Unnamed: 2  95507 non-null  object
 3   Unnamed: 3  95717 non-null  object
 4   Unnamed: 4  95722 non-null  object
 5   Unnamed: 5  95722 non-null  object
 6   Unnamed: 6  95722 non-null  object
 7   Unnamed: 7  95722 non-null  object
 8   Unnamed: 8  1 non-null      object
dtypes: object(9)
memory usage: 6.6+ MB

In [89]:
multi.shape()
## Why did this mistake happen? Also, I'm trying to know the column names but there are some spaces in between
##How do I do that?

TypeError: 'tuple' object is not callable

In [86]:
pd.read_excel("7-week-homework/multi-data.xlsx", sheet_name = "CBP")

## I'm leaving this mistake here as a personal note. I wonder why this happened when I wrote the same code
## in the cell above and it worked.

FileNotFoundError: [Errno 2] No such file or directory: '7-week-homework/multi-data.xlsx'